In [2]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import classification_report,confusion_matrix, accuracy_score
import numpy as np
from sklearn import preprocessing
from sklearn.svm import SVC
from sklearn.model_selection import GridSearchCV

import matplotlib.pyplot as plt

In [3]:
dafr = pd.read_csv('Hotel Reservations.csv')
dafr.head()

Booking_ID  no_of_adults  no_of_children  no_of_weekend_nights  \
0   INN00001             2               0                     1   
1   INN00002             2               0                     2   
2   INN00003             1               0                     2   
3   INN00004             2               0                     0   
4   INN00005             2               0                     1   

   no_of_week_nights type_of_meal_plan  required_car_parking_space  \
0                  2       Meal Plan 1                           0   
1                  3      Not Selected                           0   
2                  1       Meal Plan 1                           0   
3                  2       Meal Plan 1                           0   
4                  1      Not Selected                           0   

  room_type_reserved  lead_time  arrival_year  arrival_month  arrival_date  \
0        Room_Type 1        224          2017             10             2   
1        Room_Type 1          5          2018             11             6   
2        Room_Type 1          1          2018              2            28   
3        Room_Type 1        211          2018              5            20   
4        Room_Type 1         48          2018              4            11   

  market_segment_type  repeated_guest  no_of_previous_cancellations  \
0             Offline               0                             0   
1              Online               0                             0   
2              Online               0                             0   
3              Online               0                             0   
4              Online               0                             0   

   no_of_previous_bookings_not_canceled  avg_price_per_room  \
0                                     0               65.00   
1                                     0              106.68   
2                                     0               60.00   
3                                     0              100.00   
4                                     0               94.50   

   no_of_special_requests booking_status  
0                       0   Not_Canceled  
1                       1   Not_Canceled  
2                       0       Canceled  
3                       0       Canceled  
4                       0       Canceled

In [4]:
for c_l in list(dafr.select_dtypes(include=['object']).columns):
    dafr[c_l] = LabelEncoder().fit_transform(dafr[c_l])
    
dafr['arrival_year'] = LabelEncoder().fit_transform(dafr['arrival_year'])

scaler_dt = MinMaxScaler()
X_scaled = scaler_dt.fit_transform(dafr[['lead_time', 'arrival_month', 'arrival_date']])
dafr[['lead_time', 'arrival_month', 'arrival_date']] = X_scaled

dafr.head()

Booking_ID  no_of_adults  no_of_children  no_of_weekend_nights  \
0           0             2               0                     1   
1           1             2               0                     2   
2           2             1               0                     2   
3           3             2               0                     0   
4           4             2               0                     1   

   no_of_week_nights  type_of_meal_plan  required_car_parking_space  \
0                  2                  0                           0   
1                  3                  3                           0   
2                  1                  0                           0   
3                  2                  0                           0   
4                  1                  3                           0   

   room_type_reserved  lead_time  arrival_year  arrival_month  arrival_date  \
0                   0   0.505643             0       0.818182      0.033333   
1                   0   0.011287             1       0.909091      0.166667   
2                   0   0.002257             1       0.090909      0.900000   
3                   0   0.476298             1       0.363636      0.633333   
4                   0   0.108352             1       0.272727      0.333333   

   market_segment_type  repeated_guest  no_of_previous_cancellations  \
0                    3               0                             0   
1                    4               0                             0   
2                    4               0                             0   
3                    4               0                             0   
4                    4               0                             0   

   no_of_previous_bookings_not_canceled  avg_price_per_room  \
0                                     0               65.00   
1                                     0              106.68   
2                                     0               60.00   
3                                     0              100.00   
4                                     0               94.50   

   no_of_special_requests  booking_status  
0                       0               1  
1                       1               1  
2                       0               0  
3                       0               0  
4                       0               0

In [5]:
X = dafr.drop(['Booking_ID', 'avg_price_per_room', 'room_type_reserved'], axis = 1)
y = dafr['room_type_reserved']

In [6]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20)

In [7]:
scaler = StandardScaler()
scaler.fit(X_train)
scaled_X_train = scaler.transform(X_train) 
scaled_X_test = scaler.transform(X_test) 

In [8]:
model = SVC(C=1.0, gamma = 1.0, kernel = 'rbf')

In [9]:
model.fit(scaled_X_train,y_train)

SVC(gamma=1.0)

In [10]:
y_pred = model.predict(scaled_X_test)

In [11]:
print(classification_report(y_test, y_pred, zero_division=0.0))

              precision    recall  f1-score   support

           0       0.84      0.97      0.90      5600
           1       0.70      0.10      0.17       144
           2       0.00      0.00      0.00         1
           3       0.73      0.41      0.53      1207
           4       0.83      0.08      0.15        59
           5       0.92      0.52      0.67       210
           6       0.00      0.00      0.00        34

    accuracy                           0.84      7255
   macro avg       0.58      0.30      0.35      7255
weighted avg       0.82      0.84      0.81      7255



In [14]:
param_grid = {'C': [0.1, 1, 10, 100, 1000], 'gamma': [1,0.1,0.01,0.001,0.0001], 'kernel': ['rbf']}
grid = GridSearchCV(SVC(), param_grid, refit=True, n_jobs=-1, verbose=3)

In [15]:
grid.fit(scaled_X_train,y_train)

Fitting 5 folds for each of 25 candidates, totalling 125 fits
[CV 1/5] END ........C=0.1, gamma=1, kernel=rbf;, score=0.785 total time= 1.8min
[CV 2/5] END ........C=0.1, gamma=1, kernel=rbf;, score=0.784 total time= 1.9min
[CV 3/5] END ........C=0.1, gamma=1, kernel=rbf;, score=0.785 total time= 1.9min
[CV 4/5] END ........C=0.1, gamma=1, kernel=rbf;, score=0.783 total time= 2.0min
[CV 5/5] END ........C=0.1, gamma=1, kernel=rbf;, score=0.785 total time= 1.9min
[CV 1/5] END ......C=0.1, gamma=0.1, kernel=rbf;, score=0.844 total time=  25.1s
[CV 2/5] END ......C=0.1, gamma=0.1, kernel=rbf;, score=0.832 total time=  25.0s
[CV 3/5] END ......C=0.1, gamma=0.1, kernel=rbf;, score=0.832 total time=  26.0s
[CV 4/5] END ......C=0.1, gamma=0.1, kernel=rbf;, score=0.830 total time=  28.3s
[CV 5/5] END ......C=0.1, gamma=0.1, kernel=rbf;, score=0.839 total time=  27.7s
[CV 1/5] END .....C=0.1, gamma=0.01, kernel=rbf;, score=0.837 total time=  25.9s
[CV 2/5] END .....C=0.1, gamma=0.01, kernel=rbf

[CV 2/5] END .......C=1000, gamma=1, kernel=rbf;, score=0.813 total time= 3.0min
[CV 3/5] END .......C=1000, gamma=1, kernel=rbf;, score=0.812 total time= 3.0min
[CV 4/5] END .......C=1000, gamma=1, kernel=rbf;, score=0.814 total time= 2.5min
[CV 5/5] END .......C=1000, gamma=1, kernel=rbf;, score=0.821 total time= 2.1min
[CV 1/5] END .....C=1000, gamma=0.1, kernel=rbf;, score=0.825 total time= 3.5min
[CV 2/5] END .....C=1000, gamma=0.1, kernel=rbf;, score=0.824 total time= 4.8min
[CV 3/5] END .....C=1000, gamma=0.1, kernel=rbf;, score=0.825 total time= 4.3min
[CV 4/5] END .....C=1000, gamma=0.1, kernel=rbf;, score=0.828 total time= 4.1min
[CV 5/5] END .....C=1000, gamma=0.1, kernel=rbf;, score=0.828 total time= 2.9min
[CV 1/5] END ....C=1000, gamma=0.01, kernel=rbf;, score=0.846 total time= 3.4min
[CV 2/5] END ....C=1000, gamma=0.01, kernel=rbf;, score=0.836 total time= 4.0min
[CV 3/5] END ....C=1000, gamma=0.01, kernel=rbf;, score=0.835 total time= 4.0min
[CV 4/5] END ....C=1000, gam

GridSearchCV(estimator=SVC(), n_jobs=-1,
             param_grid={'C': [0.1, 1, 10, 100, 1000],
                         'gamma': [1, 0.1, 0.01, 0.001, 0.0001],
                         'kernel': ['rbf']},
             verbose=3)

In [16]:
grid.best_params_

{'C': 10, 'gamma': 0.1, 'kernel': 'rbf'}

In [17]:
grid.best_estimator_

SVC(C=10, gamma=0.1)

In [18]:
grid_predictions = grid.predict(scaled_X_test)

In [19]:
print(confusion_matrix(y_test,grid_predictions))

[[5498    7    0   91    2    1    1]
 [  97   40    0    1    0    5    1]
 [   1    0    0    0    0    0    0]
 [ 780    2    0  422    1    2    0]
 [  44    0    0    5    6    4    0]
 [  29    2    0    6    0  173    0]
 [   9    0    0   10    0   10    5]]


In [21]:
print(classification_report(y_test,grid_predictions, zero_division=0.0))

              precision    recall  f1-score   support

           0       0.85      0.98      0.91      5600
           1       0.78      0.28      0.41       144
           2       0.00      0.00      0.00         1
           3       0.79      0.35      0.48      1207
           4       0.67      0.10      0.18        59
           5       0.89      0.82      0.85       210
           6       0.71      0.15      0.24        34

    accuracy                           0.85      7255
   macro avg       0.67      0.38      0.44      7255
weighted avg       0.84      0.85      0.82      7255

